import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bell, Check, CheckCheck, CircleAlert, Filter, Info, RefreshCw, ShieldCheck } from "lucide-react";
import { getAlerts } from "./api";
import type { AlertRecord, DashboardData } from "./types";
const icon=(severity:string)=>severity==="critical"?CircleAlert:severity==="warning"?AlertTriangle:Info;
export default function AlertsPage({data}:{data:DashboardData}){const [history,setHistory]=useState<AlertRecord[]>([]),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[acknowledged,setAcknowledged]=useState<number[]>(()=>JSON.parse(localStorage.getItem("falcon-acknowledged-alerts")||"[]"));
 const refresh=()=>{setLoading(true);getAlerts(100).then(items=>{setHistory(items);setError(null)}).catch(reason=>setError(reason instanceof Error?reason.message:"Alert history unavailable")).finally(()=>setLoading(false))};useEffect(refresh,[]);useEffect(()=>localStorage.setItem("falcon-acknowledged-alerts",JSON.stringify(acknowledged.slice(-500))),[acknowledged]);
 const filtered=useMemo(()=>history.filter(item=>filter==="all"||item.severity===filter),[history,filter]),critical=history.filter(item=>item.severity==="critical").length,warnings=history.filter(item=>item.severity==="warning").length,unread=history.filter(item=>!acknowledged.includes(item.id)).length;
 const acknowledge=(id:number)=>setAcknowledged(items=>items.includes(id)?items:[...items,id]),ackAll=()=>setAcknowledged(items=>Array.from(new Set([...items,...history.map(item=>item.id)])));
 return <section className="content alerts-page"><div className="page-head"><div><span>OPERATIONAL NOTIFICATIONS</span><h1>Alerts and events</h1><p>Active warnings and persisted edge events from the local monitoring pipeline.</p></div><em className={`sensor-chip ${data.status.alerts.length?"is-warning":""}`}><i/> {data.status.alerts.length?`${data.status.alerts.length} ACTIVE`:"ALL CLEAR"}</em></div>
 <div className="alert-summary"><article><Bell/><span>Active alerts<b>{data.status.alerts.length}</b></span></article><article><CircleAlert/><span>Critical history<b>{critical}</b></span></article><article><AlertTriangle/><span>Warning history<b>{warnings}</b></span></article><article><CheckCheck/><span>Unacknowledged<b>{unread}</b></span></article></div>
 {data.status.alerts.length?<article className="panel active-alerts"><header><div><span>REQUIRES ATTENTION</span><h2>Active station alerts</h2></div><em>LIVE</em></header><div>{data.status.alerts.map((item,index)=>{const Icon=icon(item.severity);return <section className={`active-alert is-${item.severity}`} key={`${item.code}-${index}`}><Icon/><span><b>{item.code.replaceAll("_"," ")}</b>{item.message}</span><em>{item.severity}</em></section>})}</div></article>:<article className="panel all-clear"><ShieldCheck/><span><b>No active alerts</b>All approved monitoring channels are currently within configured limits.</span></article>}
 <article className="panel alert-history">
  <header><div><span>LOCAL DATABASE</span><h2>Alert history</h2></div><div className="alert-actions"><label><Filter/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All severity</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Information</option></select></label><button onClick={refresh} disabled={loading}><RefreshCw/> Refresh</button><button onClick={ackAll}><CheckCheck/> Acknowledge all</button></div></header>
  {error&&<div className="inline-error">{error}</div>}
  <div className="history-list">{loading&&!history.length?<div className="history-empty">Loading local alert history…</div>:!filtered.length?<div className="history-empty">No alerts match this filter.</div>:filtered.map(item=>{const Icon=icon(item.severity),ack=acknowledged.includes(item.id);return <section className={`history-item is-${item.severity} ${ack?"is-acknowledged":""}`} key={item.id}><Icon/><span><b>{item.code.replaceAll("_"," ")}</b><p>{item.message}</p><small>{new Date(item.recordedAt).toLocaleString()} · Event #{item.id}</small></span><em>{item.severity}</em><button onClick={()=>acknowledge(item.id)} disabled={ack}>{ack?<><CheckCheck/> Acknowledged</>:<><Check/> Acknowledge</>}</button></section>})}</div>
  <footer>Acknowledgement is stored locally in this browser and does not delete the edge record.</footer>
 </article></section>}
