import { lazy, Suspense, useEffect, useMemo, useRef, useState } from "react";
import { Activity, BatteryCharging, Bell, Gauge, LayoutDashboard, Menu, Navigation, Orbit, PanelLeftClose, PanelLeftOpen, Radio, Settings2, Thermometer, Waves, Wind, X, Zap } from "lucide-react";
import { getOverview } from "./api";
import type { DashboardData } from "./types";
import TelemetryChart from "./TelemetryChart";

const ActivityHub=lazy(()=>import("./ActivityHub"));
const SettingsPage=lazy(()=>import("./SettingsPage"));
const SensorsPage=lazy(()=>import("./SensorsPage"));
const MotionPage=lazy(()=>import("./MotionPage"));
const GpsPage=lazy(()=>import("./GpsPage"));
type Page="overview"|"motion"|"gps"|"sensors"|"activity"|"settings";
const navigation=[["overview","Overview","Current conditions",LayoutDashboard],["sensors","Sensors","All sensor readings",Radio],["motion","Buoy Motion","Buoy movement view",Orbit],["gps","GPS","Position and anchor distance",Navigation],["activity","Logs & Alerts","Warnings and history",Bell]] as const;
const pageTitle:Record<Page,string>={overview:"Coastal overview",motion:"Buoy motion",gps:"GPS position",sensors:"Sensor readings",activity:"Logs and alerts",settings:"Station settings"};
const n=(value:number|null|undefined,digits=1)=>value==null?"--":value.toFixed(digits);
const seaCondition=(wave:number|null|undefined)=>wave==null?"UNKNOWN":wave<.6?"CALM":wave<2.5?"MODERATE":"ROUGH";

function OverviewTrend({data}:{data:DashboardData}){
  return <><TelemetryChart points={data.wave.history.slice(-42).map(item=>({value:item.waveHeight,recordedAt:item.recordedAt}))} unit=" m" color="#3F7F7A" primaryLabel="Estimated wave height" minimumZero label="Estimated wave height" variant="standard" showSecondary={false} interactive={false}/><footer>{data.wave.calibration} · Estimated from underwater pressure</footer></>;
}
function MiniTrend({label,value,unit,color,icon:Icon,points}:{label:string;value:number|null|undefined;unit:string;color:string;icon:typeof Gauge;points:Array<number|null|undefined>}){
  const valid=points.filter((item):item is number=>typeof item==="number").slice(-30),min=Math.min(...valid),max=Math.max(...valid),range=Math.max(.01,max-min),coords=valid.map((item,index)=>`${12+index/Math.max(1,valid.length-1)*276},${82-(item-min)/range*54}`).join(" ");
  return <article className="panel mini-trend"><header><div className="panel-title"><Icon/><div><span>Recent trend</span><h2>{label}</h2></div></div><strong>{n(value,label==="Water pressure"?2:1)}{unit}</strong></header>{valid.length>1?<svg viewBox="0 0 300 96" role="img" aria-label={`${label} recent trend`}><line x1="12" y1="28" x2="288" y2="28"/><line x1="12" y1="55" x2="288" y2="55"/><line x1="12" y1="82" x2="288" y2="82"/><polyline points={coords} style={{stroke:color}}/></svg>:<p>Collecting history…</p>}</article>;
}

export default function App(){
  const [data,setData]=useState<DashboardData|null>(null),[error,setError]=useState<string|null>(null),[page,setPage]=useState<Page>("overview"),[sidebarOpen,setSidebarOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[horizon,setHorizon]=useState(10),[refreshToken,setRefreshToken]=useState(0);
  const [pollInterval,setPollInterval]=useState(()=>Number(localStorage.getItem("falcon-next-poll"))||2000);
  const [alertToast,setAlertToast]=useState<{code:string;message:string;severity:string}|null>(null),knownAlerts=useRef<Set<string>|null>(null);
  useEffect(()=>{document.documentElement.dataset.theme="light"},[]);
  useEffect(()=>localStorage.setItem("falcon-next-poll",String(pollInterval)),[pollInterval]);
  useEffect(()=>{let active=true;const refresh=async()=>{try{const next=await getOverview(horizon);if(active){setData(next);setError(null)}}catch(reason){if(active)setError(reason instanceof Error?reason.message:"Edge service unavailable")}};refresh();const timer=window.setInterval(refresh,pollInterval);return()=>{active=false;window.clearInterval(timer)}},[horizon,pollInterval,refreshToken]);
  useEffect(()=>{if(!data)return;const next=new Set(data.status.alerts.map(item=>item.code));if(knownAlerts.current){const fresh=data.status.alerts.find(item=>!knownAlerts.current?.has(item.code));if(fresh){setAlertToast(fresh);window.setTimeout(()=>setAlertToast(null),8000)}}knownAlerts.current=next},[data]);
  const lastUpdate=useMemo(()=>data?.status.lastUpdate?new Date(data.status.lastUpdate).toLocaleTimeString():"--:--:--",[data]);
  const online=data?.status.system==="ONLINE";
  const fallback=<div className="loading"><img src="/falcon-logo.jpg" alt=""/><b>Loading FALCON data</b><span>Reading local edge records…</span></div>;
  return <div className={`app ${collapsed?"is-collapsed":""} ${sidebarOpen?"is-menu-open":""}`}>
    <button className="scrim" onClick={()=>setSidebarOpen(false)} aria-label="Close navigation"/>
    <aside className="sidebar"><div className="brand"><img src="/falcon-logo.jpg" alt="FALCON logo"/><div><strong>FALCON-01</strong><span>COASTAL STATION</span></div></div><nav>{navigation.map(([key,label,detail,Icon])=><button key={key} className={`nav-item ${page===key?"is-active":""}`} onClick={()=>{setPage(key);setSidebarOpen(false)}}><Icon/><span><b>{label}</b><small>{detail}</small></span></button>)}</nav><div className="side-foot"><i className={online?"online":""}/><span><b>{online?"EDGE ONLINE":"EDGE CONNECTING"}</b><small>ORANGE PI · LOCAL EDGE</small></span></div></aside>
    <main><header className="topbar"><div className="title"><button className="mobile-menu" onClick={()=>setSidebarOpen(true)} aria-label="Open navigation"><Menu/></button><button className="collapse" onClick={()=>setCollapsed(!collapsed)} aria-label="Toggle sidebar">{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button><div><span>PROJECT FALCON</span><h1>{pageTitle[page]}</h1></div></div><div className="top-actions"><div><span>Last update</span><b>{lastUpdate}</b></div><div><span>Source</span><b>{data?.status.dataSource?.toUpperCase()||"--"}</b></div><button className="notification-button" onClick={()=>setPage("activity")} title="Logs & Alerts" aria-label="Open notifications"><Bell/>{data?.status.alerts.length?<b>{data.status.alerts.length}</b>:null}</button><button onClick={()=>setPage("settings")} title="Settings" aria-label="Open settings"><Settings2/></button><span className={`live ${online?"is-online":""}`}><i/>{online?(data?.current.system.labels[0]||"LIVE"):"OFFLINE"}</span></div></header>
    {error&&<div className="error-banner"><Activity/><span><b>Edge connection interrupted</b>{error}</span></div>}
    {alertToast&&<button className={`alert-toast is-${alertToast.severity}`} onClick={()=>{setPage("activity");setAlertToast(null)}}><Bell/><span><b>{alertToast.code.replaceAll("_"," ")}</b>{alertToast.message}</span><X/></button>}
    {!data?fallback:page==="motion"?<Suspense fallback={fallback}><MotionPage data={data}/></Suspense>:page==="gps"?<Suspense fallback={fallback}><GpsPage data={data}/></Suspense>:page==="sensors"?<Suspense fallback={fallback}><SensorsPage data={data}/></Suspense>:page==="activity"?<Suspense fallback={fallback}><ActivityHub data={data}/></Suspense>:page==="settings"?<Suspense fallback={fallback}><SettingsPage horizon={horizon} onHorizon={setHorizon} pollInterval={pollInterval} onPollInterval={setPollInterval} onRefresh={()=>setRefreshToken(value=>value+1)}/></Suspense>:<section className="content overview-page operator-overview">
      <div className="dashboard-grid"><article className="panel chart-panel sensor-history-card"><header><div className="panel-title"><Waves/><div><span>Main reading</span><h2>Estimated wave height</h2></div></div><strong className="wave-value">{n(data.wave.waveHeight,2)} m</strong></header><div className="sea-condition-summary"><div><span>Current sea condition</span><strong>{seaCondition(data.wave.waveHeight)}</strong></div><div className="sea-condition-scale" aria-label={`Current sea condition: ${seaCondition(data.wave.waveHeight)}`}>{(["CALM","MODERATE","ROUGH"] as const).map(condition=><span key={condition} className={seaCondition(data.wave.waveHeight)===condition?`is-current is-${condition.toLowerCase()}`:""}>{condition}</span>)}</div><small>Calm below 0.60 m · Moderate 0.60–2.49 m · Rough 2.50 m and above</small></div><OverviewTrend data={data}/></article>
      <article className="panel snapshot"><header><div className="panel-title"><Gauge/><div><span>Current readings</span><h2>Station status</h2></div></div><em className={data.current.security.state==="SECURE"?"status-good":"status-danger"}>{data.current.security.state}</em></header><dl><div><dt><Wind/>Wind</dt><dd>{n(data.status.windSpeed)} km/h · {data.status.windDirection}</dd></div><div><dt><Waves/>Pressure</dt><dd>{n(data.wave.filteredPressure,2)} kPa</dd></div><div><dt><Navigation/>GPS security</dt><dd>{data.current.security.geofenceState}</dd></div><div><dt><BatteryCharging/>Battery</dt><dd>{n(data.battery.percentage,0)}% · {data.battery.status}</dd></div><div><dt><Zap/>Solar</dt><dd>{data.solar.status} · {n(data.solar.power)} W</dd></div><div><dt><Thermometer/>Temperature</dt><dd>Water {n(data.current.environment.waterTemperature)} °C<br/>Enclosure {n(data.status.internalTemperature)} °C</dd></div></dl></article></div>
      <div className="always-visible-trends"><MiniTrend label="Water pressure" value={data.wave.filteredPressure} unit=" kPa" color="#6B8FA3" icon={Gauge} points={data.wave.history.map(item=>item.filteredPressure)}/><MiniTrend label="Wind speed" value={data.status.windSpeed} unit=" km/h" color="#3F7F7A" icon={Wind} points={data.status.sensorHistory.map(item=>item.windSpeed)}/><MiniTrend label="GPS distance from anchor" value={data.gps.anchorDistanceMeters} unit=" m" color="#9A7C55" icon={Navigation} points={data.status.sensorHistory.map(item=>item.anchorDistance)}/></div>
    </section>}</main>
  </div>;
}
