import { lazy, Suspense, useEffect, useMemo, useRef, useState } from "react";
import { Activity, BatteryCharging, Bell, Bot, Gauge, LayoutDashboard, Menu, Moon, Navigation, PanelLeftClose, PanelLeftOpen, Radio, Satellite, Settings2, ShieldCheck, Sparkles, Sun, Thermometer, Waves, Wind, X, Zap } from "lucide-react";
import { getOverview } from "./api";
import type { DashboardData } from "./types";
import TelemetryChart from "./TelemetryChart";

const ActivityHub=lazy(()=>import("./ActivityHub"));
const SettingsPage=lazy(()=>import("./SettingsPage"));
const SensorsPage=lazy(()=>import("./SensorsPage"));
type Page="overview"|"sensors"|"activity"|"settings";
const navigation=[["overview","Overview","Coastal monitoring",LayoutDashboard],["sensors","Sensors","All readings & quality",Radio],["activity","Logs & Alerts","Events & local records",Bell]] as const;
const pageTitle:Record<Page,string>={overview:"Coastal overview",sensors:"Sensor readings",activity:"Logs and alerts",settings:"Station settings"};
const n=(value:number|null|undefined,digits=1)=>value==null?"--":value.toFixed(digits);

function Trend({data,showPrediction}:{data:DashboardData;showPrediction:boolean}){
  return <TelemetryChart points={data.wave.history.slice(-42).map(item=>({value:item.waveHeight,recordedAt:item.recordedAt}))} forecast={showPrediction?data.ai.predictedWaveHeight:null} forecastLabel={`${data.ai.horizonMinutes} MIN OPTIONAL AI`} unit=" m" color="#70aeb7" secondaryColor="#aa8a5e" primaryLabel="Pressure estimate" secondaryLabel="Optional prediction" minimumZero label="Estimated wave height" variant="minimal" showSecondary/>;
}

export default function App(){
  const [data,setData]=useState<DashboardData|null>(null),[error,setError]=useState<string|null>(null),[page,setPage]=useState<Page>("overview"),[sidebarOpen,setSidebarOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[horizon,setHorizon]=useState(10),[refreshToken,setRefreshToken]=useState(0),[showAi,setShowAi]=useState(false);
  const [pollInterval,setPollInterval]=useState(()=>Number(localStorage.getItem("falcon-next-poll"))||2000);
  const [theme,setTheme]=useState<"dark"|"light">(()=>(localStorage.getItem("falcon-next-theme") as "dark"|"light")||"dark");
  const [alertToast,setAlertToast]=useState<{code:string;message:string;severity:string}|null>(null),knownAlerts=useRef<Set<string>|null>(null);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("falcon-next-theme",theme)},[theme]);
  useEffect(()=>localStorage.setItem("falcon-next-poll",String(pollInterval)),[pollInterval]);
  useEffect(()=>{let active=true;const refresh=async()=>{try{const next=await getOverview(horizon);if(active){setData(next);setError(null)}}catch(reason){if(active)setError(reason instanceof Error?reason.message:"Edge service unavailable")}};refresh();const timer=window.setInterval(refresh,pollInterval);return()=>{active=false;window.clearInterval(timer)}},[horizon,pollInterval,refreshToken]);
  useEffect(()=>{if(!data)return;const next=new Set(data.status.alerts.map(item=>item.code));if(knownAlerts.current){const fresh=data.status.alerts.find(item=>!knownAlerts.current?.has(item.code));if(fresh){setAlertToast(fresh);window.setTimeout(()=>setAlertToast(null),8000)}}knownAlerts.current=next},[data]);
  const lastUpdate=useMemo(()=>data?.status.lastUpdate?new Date(data.status.lastUpdate).toLocaleTimeString():"--:--:--",[data]);
  const online=data?.status.system==="ONLINE";
  const fallback=<div className="loading"><img src="/falcon-logo.jpg" alt=""/><b>Loading FALCON data</b><span>Reading local edge records…</span></div>;
  return <div className={`app ${collapsed?"is-collapsed":""} ${sidebarOpen?"is-menu-open":""}`}>
    <button className="scrim" onClick={()=>setSidebarOpen(false)} aria-label="Close navigation"/>
    <aside className="sidebar"><div className="brand"><img src="/falcon-logo.jpg" alt="FALCON logo"/><div><strong>FALCON-01</strong><span>COASTAL STATION</span></div></div><nav>{navigation.map(([key,label,detail,Icon])=><button key={key} className={`nav-item ${page===key?"is-active":""}`} onClick={()=>{setPage(key);setSidebarOpen(false)}}><Icon/><span><b>{label}</b><small>{detail}</small></span></button>)}</nav><div className="side-foot"><i className={online?"online":""}/><span><b>{online?"EDGE ONLINE":"EDGE CONNECTING"}</b><small>ORANGE PI · LOCAL EDGE</small></span></div></aside>
    <main><header className="topbar"><div className="title"><button className="mobile-menu" onClick={()=>setSidebarOpen(true)} aria-label="Open navigation"><Menu/></button><button className="collapse" onClick={()=>setCollapsed(!collapsed)} aria-label="Toggle sidebar">{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button><div><span>PROJECT FALCON / COASTAL OBSERVATION</span><h1>{pageTitle[page]}</h1></div></div><div className="top-actions"><div><span>LAST UPDATE</span><b>{lastUpdate}</b></div><div><span>SOURCE</span><b>{data?.status.dataSource?.toUpperCase()||"--"}</b></div><button className="notification-button" onClick={()=>setPage("activity")} title="Logs & Alerts"><Bell/>{data?.status.alerts.length?<b>{data.status.alerts.length}</b>:null}</button><button onClick={()=>setPage("settings")} title="Settings"><Settings2/></button><button onClick={()=>setTheme(theme==="dark"?"light":"dark")} title="Theme">{theme==="dark"?<Sun/>:<Moon/>}</button><span className={`live ${online?"is-online":""}`}><i/>{online?(data?.current.system.labels[0]||"LIVE"):"OFFLINE"}</span></div></header>
    {error&&<div className="error-banner"><Activity/><span><b>Edge connection interrupted</b>{error}</span></div>}
    {alertToast&&<button className={`alert-toast is-${alertToast.severity}`} onClick={()=>{setPage("activity");setAlertToast(null)}}><Bell/><span><b>{alertToast.code.replaceAll("_"," ")}</b>{alertToast.message}</span><X/></button>}
    {!data?fallback:page==="sensors"?<Suspense fallback={fallback}><SensorsPage data={data}/></Suspense>:page==="activity"?<Suspense fallback={fallback}><ActivityHub data={data}/></Suspense>:page==="settings"?<Suspense fallback={fallback}><SettingsPage theme={theme} onTheme={setTheme} horizon={horizon} onHorizon={setHorizon} pollInterval={pollInterval} onPollInterval={setPollInterval} onRefresh={()=>setRefreshToken(value=>value+1)}/></Suspense>:<section className="content overview-page">
      <div className="summary"><article><ShieldCheck/><span>Security<b className={data.current.security.state==="SECURE"?"good":"warn"}>{data.current.security.state}</b><small>GPS geofence + tamper</small></span></article><article><Waves/><span>Estimated wave<b>{n(data.wave.waveHeight,2)} m</b><small>{data.wave.calibration}</small></span></article><article><Radio/><span>Data state<b>{data.current.system.labels.join(" · ")}</b><small>clearly identified source</small></span></article><article><Bell/><span>Active alerts<b>{data.status.alerts.length}</b><small>{data.status.alerts.length?"review required":"no active warning"}</small></span></article></div>
      <div className="ribbon"><span><Wind/>Wind<b>{n(data.status.windSpeed)} km/h · {data.status.windDirection||"--"}</b></span><span><Satellite/>GPS<b>{data.gps.valid?`${data.gps.fix} · ${data.gps.satellites} SAT`:"NO FIX"}</b></span><span><BatteryCharging/>Battery<b>{n(data.battery.percentage,0)}%</b></span><span><Thermometer/>Water<b>{n(data.current.environment.waterTemperature)} °C</b></span><span><Bell/>Alerts<b>{data.status.alerts.length}</b></span></div>
      <div className="dashboard-grid"><article className="panel chart-panel"><header><div className="panel-title"><Waves/><div><span>PRESSURE-BASED ESTIMATE</span><h2>Estimated wave height</h2></div></div><em>{data.wave.waveHeightState}</em></header><div className="prediction-controls"><div className="readouts"><span>Filtered pressure <b>{n(data.wave.filteredPressure,2)} kPa</b></span><span>Estimated wave <b>{n(data.wave.waveHeight,2)} m</b></span>{showAi&&<span>OPTIONAL AI · {data.ai.horizonMinutes} min <b>{n(data.ai.predictedWaveHeight,2)} m</b></span>}</div><button className={showAi?"is-active":""} onClick={()=>setShowAi(value=>!value)}><Sparkles/>{showAi?"Hide optional AI":"Show optional AI"}</button></div><Trend data={data} showPrediction={showAi}/><footer>{data.wave.calibration} · ESTIMATE FROM UNDERWATER PRESSURE VARIATION · NOT AN OFFICIAL FORECAST</footer></article>
      <article className="panel snapshot"><header><div className="panel-title"><Gauge/><div><span>COASTAL STATUS</span><h2>Environment and station</h2></div></div><em>{data.current.system.labels.join(" · ")}</em></header><dl><div><dt><Wind/>Wind</dt><dd>{n(data.status.windSpeed)} km/h · {data.status.windDirection}</dd></div><div><dt><Waves/>Pressure</dt><dd>{n(data.wave.filteredPressure,2)} kPa</dd></div><div><dt><Navigation/>GPS security</dt><dd>{data.current.security.geofenceState} · {n(data.current.security.distanceMeters)} m</dd></div><div><dt><BatteryCharging/>Battery</dt><dd>{n(data.battery.percentage,0)}% · {data.battery.status}</dd></div><div><dt><Zap/>Solar</dt><dd>{data.solar.status} · {n(data.solar.power)} W</dd></div><div><dt><Thermometer/>Water / enclosure</dt><dd>{n(data.current.environment.waterTemperature)} / {n(data.status.internalTemperature)} °C</dd></div></dl></article></div>
      <article className={`panel assistant-card is-${data.current.assistant.state.toLowerCase()}`}><Bot/><span><small>FALCON ASSISTANT · RULE-BASED · OPTIONAL</small><b>{data.current.assistant.state}</b><p>{data.current.assistant.message}</p></span></article>
    </section>}</main>
  </div>;
}
