import { lazy, Suspense, useEffect, useMemo, useRef, useState } from "react";
import { Activity, BatteryCharging, Bell, Gauge, LayoutDashboard, Menu, Navigation, Orbit, PanelLeftClose, PanelLeftOpen, Radio, Settings2, Thermometer, Waves, Wind, X, Zap } from "lucide-react";
import { getOverview } from "./api";
import type { DashboardData } from "./types";
import TelemetryChart from "./TelemetryChart";

const ActivityHub=lazy(()=>import("./ActivityHub"));
const SettingsPage=lazy(()=>import("./SettingsPage"));
const SensorsPage=lazy(()=>import("./SensorsPage"));
const MotionPage=lazy(()=>import("./MotionPage"));
type Page="overview"|"motion"|"sensors"|"activity"|"settings";
type OverviewMetric="wave"|"pressure"|"wind"|"gps"|"temperature"|"battery"|"solar";
const navigation=[["overview","Overview","Current conditions",LayoutDashboard],["sensors","Sensors","All sensor readings",Radio],["activity","Logs & Alerts","Warnings and records",Bell],["motion","Buoy Motion","Buoy movement view",Orbit]] as const;
const pageTitle:Record<Page,string>={overview:"Coastal overview",motion:"Buoy motion",sensors:"Sensor readings",activity:"Logs and alerts",settings:"Station settings"};
const n=(value:number|null|undefined,digits=1)=>value==null?"--":value.toFixed(digits);

const metricOptions=[["wave","Wave height",Waves],["pressure","Water pressure",Gauge],["wind","Wind speed",Wind],["gps","GPS distance",Navigation],["temperature","Water temperature",Thermometer],["battery","Battery",BatteryCharging],["solar","Solar power",Zap]] as const;
function OverviewTrend({data,metric}:{data:DashboardData;metric:OverviewMetric}){
  const history=data.status.sensorHistory.slice(-42);
  const config=metric==="pressure"?{label:"Water pressure",unit:" kPa",value:data.wave.filteredPressure,color:"#2563EB",points:data.wave.history.slice(-42).map(item=>({value:item.filteredPressure??null,recordedAt:item.recordedAt})),note:"Filtered underwater-pressure readings"}:
    metric==="wind"?{label:"Wind speed",unit:" km/h",value:data.status.windSpeed,color:"#0F766E",points:history.map(item=>({value:item.windSpeed,recordedAt:item.recordedAt})),note:"Recent wind-speed readings"}:
    metric==="gps"?{label:"GPS distance from anchor",unit:" m",value:data.gps.anchorDistanceMeters,color:"#D97706",points:history.map(item=>({value:item.anchorDistance,recordedAt:item.recordedAt})),note:"Distance from the saved deployment point"}:
    metric==="temperature"?{label:"Water temperature",unit:" °C",value:data.current.environment.waterTemperature,color:"#2563EB",points:history.map(item=>({value:item.waterTemperature,recordedAt:item.recordedAt})),note:"Recent water-temperature readings"}:
    metric==="battery"?{label:"Battery level",unit:"%",value:data.battery.percentage,color:"#16A34A",points:data.battery.history.slice(-42).map(item=>({value:item.percentage,recordedAt:item.recordedAt})),note:"Remaining battery level"}:
    metric==="solar"?{label:"Solar power",unit:" W",value:data.solar.power,color:"#D97706",points:history.map(item=>({value:item.solarPower,recordedAt:item.recordedAt})),note:"Power currently produced by the solar system"}:
    {label:"Estimated wave height",unit:" m",value:data.wave.waveHeight,color:"#0F766E",points:data.wave.history.slice(-42).map(item=>({value:item.waveHeight,recordedAt:item.recordedAt})),note:"Estimated from underwater-pressure readings"};
  return <><TelemetryChart points={config.points} unit={config.unit} color={config.color} primaryLabel={config.label} minimumZero={metric==="wave"||metric==="gps"||metric==="battery"||metric==="solar"} label={config.label} variant="minimal" showSecondary={false}/><footer>{config.note}</footer></>;
}

export default function App(){
  const [data,setData]=useState<DashboardData|null>(null),[error,setError]=useState<string|null>(null),[page,setPage]=useState<Page>("overview"),[overviewMetric,setOverviewMetric]=useState<OverviewMetric>("wave"),[sidebarOpen,setSidebarOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[horizon,setHorizon]=useState(10),[refreshToken,setRefreshToken]=useState(0);
  const [pollInterval,setPollInterval]=useState(()=>Number(localStorage.getItem("falcon-next-poll"))||2000);
  const [alertToast,setAlertToast]=useState<{code:string;message:string;severity:string}|null>(null),knownAlerts=useRef<Set<string>|null>(null);
  useEffect(()=>{document.documentElement.dataset.theme="light"},[]);
  useEffect(()=>localStorage.setItem("falcon-next-poll",String(pollInterval)),[pollInterval]);
  useEffect(()=>{let active=true;const refresh=async()=>{try{const next=await getOverview(horizon);if(active){setData(next);setError(null)}}catch(reason){if(active)setError(reason instanceof Error?reason.message:"Edge service unavailable")}};refresh();const timer=window.setInterval(refresh,pollInterval);return()=>{active=false;window.clearInterval(timer)}},[horizon,pollInterval,refreshToken]);
  useEffect(()=>{if(!data)return;const next=new Set(data.status.alerts.map(item=>item.code));if(knownAlerts.current){const fresh=data.status.alerts.find(item=>!knownAlerts.current?.has(item.code));if(fresh){setAlertToast(fresh);window.setTimeout(()=>setAlertToast(null),8000)}}knownAlerts.current=next},[data]);
  const lastUpdate=useMemo(()=>data?.status.lastUpdate?new Date(data.status.lastUpdate).toLocaleTimeString():"--:--:--",[data]);
  const online=data?.status.system==="ONLINE";
  const fallback=<div className="loading"><img src="/falcon-logo.jpg" alt=""/><b>Loading FALCON data</b><span>Reading local edge records…</span></div>;
  return <div className={`app ${collapsed?"is-collapsed":""} ${sidebarOpen?"is-menu-open":""}`}>
    <button className="scrim" onClick={()=>setSidebarOpen(false)} aria-label="Close navigation"/>
    <aside className="sidebar"><div className="brand"><img src="/falcon-logo.jpg" alt="FALCON logo"/><div><strong>FALCON-01</strong><span>COASTAL STATION</span></div></div><nav>{navigation.map(([key,label,detail,Icon])=><button key={key} className={`nav-item ${page===key?"is-active":""}`} onClick={()=>{setPage(key);setSidebarOpen(false)}}><Icon/><span><b>{label}</b><small>{detail}</small></span></button>)}</nav><div className="side-foot"><i className={online?"online":""}/><span><b>{online?"EDGE ONLINE":"EDGE CONNECTING"}</b><small>ORANGE PI · LOCAL EDGE</small></span></div></aside>
    <main><header className="topbar"><div className="title"><button className="mobile-menu" onClick={()=>setSidebarOpen(true)} aria-label="Open navigation"><Menu/></button><button className="collapse" onClick={()=>setCollapsed(!collapsed)} aria-label="Toggle sidebar">{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button><div><span>PROJECT FALCON</span><h1>{pageTitle[page]}</h1></div></div><div className="top-actions"><div><span>Last update</span><b>{lastUpdate}</b></div><div><span>Source</span><b>{data?.status.dataSource?.toUpperCase()||"--"}</b></div><button className="notification-button" onClick={()=>setPage("activity")} title="Logs & Alerts" aria-label="Open notifications"><Bell/>{data?.status.alerts.length?<b>{data.status.alerts.length}</b>:null}</button><button onClick={()=>setPage("settings")} title="Settings" aria-label="Open settings"><Settings2/></button><span className={`live ${online?"is-online":""}`}><i/>{online?(data?.current.system.labels[0]||"LIVE"):"OFFLINE"}</span></div></header>
    {error&&<div className="error-banner"><Activity/><span><b>Edge connection interrupted</b>{error}</span></div>}
    {alertToast&&<button className={`alert-toast is-${alertToast.severity}`} onClick={()=>{setPage("activity");setAlertToast(null)}}><Bell/><span><b>{alertToast.code.replaceAll("_"," ")}</b>{alertToast.message}</span><X/></button>}
    {!data?fallback:page==="motion"?<Suspense fallback={fallback}><MotionPage data={data}/></Suspense>:page==="sensors"?<Suspense fallback={fallback}><SensorsPage data={data}/></Suspense>:page==="activity"?<Suspense fallback={fallback}><ActivityHub data={data}/></Suspense>:page==="settings"?<Suspense fallback={fallback}><SettingsPage horizon={horizon} onHorizon={setHorizon} pollInterval={pollInterval} onPollInterval={setPollInterval} onRefresh={()=>setRefreshToken(value=>value+1)}/></Suspense>:<section className="content overview-page operator-overview">
      <div className="dashboard-grid"><article className="panel chart-panel sensor-history-card"><header><div className="panel-title">{(()=>{const Icon=metricOptions.find(item=>item[0]===overviewMetric)![2];return <Icon/>})()}<div><span>Recent sensor readings</span><h2>{overviewMetric==="gps"?"GPS distance from anchor":metricOptions.find(item=>item[0]===overviewMetric)![1]}</h2></div></div><strong className="wave-value">{overviewMetric==="wave"?`${n(data.wave.waveHeight,2)} m`:overviewMetric==="pressure"?`${n(data.wave.filteredPressure,2)} kPa`:overviewMetric==="wind"?`${n(data.status.windSpeed)} km/h`:overviewMetric==="gps"?`${n(data.gps.anchorDistanceMeters)} m`:overviewMetric==="temperature"?`${n(data.current.environment.waterTemperature)} °C`:overviewMetric==="battery"?`${n(data.battery.percentage,0)}%`:`${n(data.solar.power)} W`}</strong></header><div className="sensor-graph-tabs" role="tablist" aria-label="Choose sensor graph">{metricOptions.map(([key,label,Icon])=><button key={key} type="button" role="tab" aria-selected={overviewMetric===key} className={overviewMetric===key?"is-active":""} onClick={()=>setOverviewMetric(key)}><Icon/><span>{label}</span></button>)}</div><OverviewTrend data={data} metric={overviewMetric}/></article>
      <article className="panel snapshot"><header><div className="panel-title"><Gauge/><div><span>Current readings</span><h2>Station status</h2></div></div><em className={data.current.security.state==="SECURE"?"status-good":"status-danger"}>{data.current.security.state}</em></header><dl><div><dt><Wind/>Wind</dt><dd>{n(data.status.windSpeed)} km/h · {data.status.windDirection}</dd></div><div><dt><Waves/>Pressure</dt><dd>{n(data.wave.filteredPressure,2)} kPa</dd></div><div><dt><Navigation/>GPS security</dt><dd>{data.current.security.geofenceState}</dd></div><div><dt><BatteryCharging/>Battery</dt><dd>{n(data.battery.percentage,0)}% · {data.battery.status}</dd></div><div><dt><Zap/>Solar</dt><dd>{data.solar.status} · {n(data.solar.power)} W</dd></div><div><dt><Thermometer/>Temperature</dt><dd>Water {n(data.current.environment.waterTemperature)} °C<br/>Enclosure {n(data.status.internalTemperature)} °C</dd></div></dl></article></div>
    </section>}</main>
  </div>;
}
