import { Compass, MapPin, Navigation, Radio, Satellite } from "lucide-react";
import GpsMap from "./GpsMap";
import type { DashboardData } from "./types";
const n=(value:number|null|undefined,digits=1)=>value==null?"--":value.toFixed(digits);
export default function GpsPage({data}:{data:DashboardData}){const {gps}=data;return <section className="content gps-page"><div className="page-head"><div><span>POSITION & GEOFENCE</span><h1>GPS and drift</h1><p>Live GNSS position relative to the Puerto Princesa coastal deployment reference.</p></div><em className={`sensor-chip ${gps.valid?"":"is-warning"}`}><i/> {gps.fix} FIX · {gps.satellites} SAT</em></div>
 <div className="gps-layout"><article className="panel map-panel"><header><div><span>LIVE POSITION</span><h2>Puerto Princesa City, Palawan Coast</h2></div><em>{gps.deploymentReferenceState.replaceAll("_"," ")}</em></header><GpsMap gps={gps}/><footer>Map tiles require internet · sensor position remains available locally.</footer></article>
 <aside className="gps-side"><article className="panel coordinates"><header><div><span>GNSS RECEIVER</span><h2>Position solution</h2></div><Satellite/></header><strong>{gps.valid&&gps.latitude!=null&&gps.longitude!=null?`${gps.latitude.toFixed(5)}° N` : "Coordinates unavailable"}</strong><strong>{gps.valid&&gps.longitude!=null?`${gps.longitude.toFixed(5)}° E`:""}</strong><dl><div><dt>Horizontal accuracy</dt><dd>±{n(gps.horizontalAccuracyMeters)} m</dd></div><div><dt>Signal quality</dt><dd className="good">{gps.signalQuality}</dd></div><div><dt>Satellites</dt><dd>{gps.satellites}</dd></div></dl></article>
 <article className="panel drift-card"><header><div><span>ANCHOR WATCH</span><h2>Drift assessment</h2></div><Navigation/></header><div className="drift-status"><MapPin/><span>Geofence<b className={gps.driftStatus==="SECURE"?"good":"warn"}>{gps.driftStatus}</b></span></div><dl><div><dt>Anchor distance</dt><dd>{n(gps.anchorDistanceMeters)} m</dd></div><div><dt>Surface speed</dt><dd>{n(gps.surfaceSpeedKnots,2)} kn</dd></div><div><dt>Heading</dt><dd>{n(gps.headingDegrees)}°</dd></div></dl></article>
 <article className="panel gps-source"><span><Radio/> Position source<b>GPS determines location</b></span><span><Compass/> Orientation source<b>IMU determines heading</b></span></article></aside></div></section>}
