import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Download, FileJson, Filter, RefreshCw } from "lucide-react";
import { getLogs } from "./api";
import type { LogsPayload } from "./types";
import TelemetryChart from "./TelemetryChart";
const empty:LogsPayload={telemetry:[],predictions:[],alerts:[],events:[]};
const download=(name:string,type:string,content:string)=>{const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
export default function HistoryPage(){const [logs,setLogs]=useState(empty),[loading,setLoading]=useState(true),[from,setFrom]=useState(""),[to,setTo]=useState("");const load=()=>{setLoading(true);getLogs(200).then(setLogs).finally(()=>setLoading(false))};useEffect(load,[]);const rows=useMemo(()=>logs.telemetry.filter(row=>(!from||row.recordedAt>=new Date(`${from}T00:00:00`).toISOString())&&(!to||row.recordedAt<=new Date(`${to}T23:59:59`).toISOString())),[from,to,logs.telemetry]);const csv=()=>{const head="recordedAt,pressure,waveHeight,roll,pitch,windSpeed,source\n",body=rows.map(row=>[row.recordedAt,row.waterPressure??"",row.waveLevel??"",row.roll??"",row.pitch??"",row.windSpeed??"",row.source].join(",")).join("\n");download("falcon-history.csv","text/csv",head+body)};return <section className="content engineering-page"><div className="page-head"><div><span>LOCAL OPERATIONAL ARCHIVE</span><h1>Historical data</h1><p>Filter, inspect, and export locally stored environmental and prediction records.</p></div><div className="history-actions"><button onClick={load}><RefreshCw/>Refresh</button><button onClick={csv}><Download/>CSV</button><button onClick={()=>download("falcon-history.json","application/json",JSON.stringify({telemetry:rows,predictions:logs.predictions},null,2))}><FileJson/>JSON</button></div></div><div className="history-filter panel"><Filter/><label>From <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><span><CalendarDays/>{rows.length} telemetry records · {logs.predictions.length} predictions</span></div>{loading?<div className="chart-empty">Loading local history…</div>:<div className="history-grid"><HistoryCard title="Historical pressure" unit=" kPa" color="#68aeb7" points={rows.map(row=>({recordedAt:row.recordedAt,value:typeof row.waterPressure==="number"?row.waterPressure:null}))}/><HistoryCard title="Historical wave height" unit=" m" color="#73b9c0" points={rows.map(row=>({recordedAt:row.recordedAt,value:row.waveLevel}))}/><HistoryCard title="Historical motion · roll" unit="°" color="#8d82aa" points={rows.map(row=>({recordedAt:row.recordedAt,value:typeof row.roll==="number"?row.roll:null}))}/><HistoryCard title="Historical wind" unit=" km/h" color="#7ea38d" points={rows.map(row=>({recordedAt:row.recordedAt,value:row.windSpeed}))}/><HistoryCard title="Historical predictions" unit=" m" color="#bd8c55" points={logs.predictions.map(row=>({recordedAt:row.generatedAt,value:row.predictedWaveHeight}))}/></div>}</section>}
function HistoryCard({title,points,unit,color}:{title:string;points:Array<{recordedAt:string;value:number|null}>;unit:string;color:string}){return <article className="panel history-card"><header><div><span>ARCHIVED SERIES</span><h2>{title}</h2></div></header><TelemetryChart points={points.slice(-80)} unit={unit} color={color} label={title} variant="minimal"/><footer>{title.includes("predictions")?"Experimental research predictions · not an official forecast":"Local records · source labels retained in export"}</footer></article>}
