import { useEffect, useMemo, useState } from "react";
import { Bell, BrainCircuit, Database, Download, FileJson, Radio, RefreshCw, Search } from "lucide-react";
import { getLogs } from "./api";
import type { LogsPayload } from "./types";
const empty:LogsPayload={telemetry:[],predictions:[],alerts:[],events:[]},n=(value:number|null|undefined,digits=2)=>value==null?"--":value.toFixed(digits);
type Tab=keyof LogsPayload;
const download=(name:string,type:string,content:string)=>{const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)};
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
export default function LogsPage(){const [logs,setLogs]=useState(empty),[tab,setTab]=useState<Tab>("telemetry"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const refresh=()=>{setLoading(true);getLogs(100).then(value=>{setLogs(value);setError(null)}).catch(reason=>setError(reason instanceof Error?reason.message:"Logs unavailable")).finally(()=>setLoading(false))};useEffect(refresh,[]);
 const rows=useMemo(()=>logs[tab].filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase())),[logs,tab,query]);const exportJson=()=>download(`falcon-${tab}.json`,"application/json",JSON.stringify(rows,null,2));const exportCsv=()=>{if(!rows.length)return;const keys=Object.keys(rows[0]);download(`falcon-${tab}.csv`,"text/csv",[keys.map(csvCell).join(","),...rows.map(row=>keys.map(key=>csvCell((row as unknown as Record<string,unknown>)[key] instanceof Object?JSON.stringify((row as unknown as Record<string,unknown>)[key]):(row as unknown as Record<string,unknown>)[key])).join(","))].join("\n"))};
 return <section className="content logs-page"><div className="page-head"><div><span>LOCAL DATA ARCHIVE</span><h1>Saved records</h1><p>Search saved readings, AI predictions, alerts, and station events.</p></div><em className="sensor-chip"><i/> SQLITE · LOCAL</em></div>
 <div className="log-summary"><article><Database/><span>Saved readings<b>{logs.telemetry.length}</b></span></article><article><BrainCircuit/><span>AI predictions<b>{logs.predictions.length}</b></span></article><article><Bell/><span>Alert records<b>{logs.alerts.length}</b></span></article><article><Radio/><span>System events<b>{logs.events.length}</b></span></article></div>
 <article className="panel logs-table-panel"><header><div className="log-tabs">{(["telemetry","predictions","alerts","events"] as Tab[]).map(value=><button className={tab===value?"is-active":""} onClick={()=>setTab(value)} key={value}>{{telemetry:"Readings",predictions:"AI predictions",alerts:"Alerts",events:"System events"}[value]}</button>)}</div><div className="log-tools"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} aria-label="Search records" placeholder="Search records"/></label><button onClick={refresh} disabled={loading}><RefreshCw/>Refresh</button><button onClick={exportCsv} disabled={!rows.length}><Download/>CSV</button><button onClick={exportJson} disabled={!rows.length}><FileJson/>JSON</button></div></header>{error&&<div className="inline-error">{error}</div>}<div className="log-table-scroll"><table>{tab==="telemetry"?<><thead><tr><th>Timestamp</th><th>Wave</th><th>Battery</th><th>Temperature</th><th>Wind</th><th>Scenario</th><th>Source</th></tr></thead><tbody>{rows.map(raw=>{const row=raw as LogsPayload["telemetry"][number];return <tr key={row.id}><td>{new Date(row.recordedAt).toLocaleString()}</td><td>{n(row.waveLevel)} m</td><td>{n(row.battery,0)}%</td><td>{n(row.internalTemperature,1)} °C</td><td>{n(row.windSpeed,1)} km/h</td><td>{row.scenario}</td><td>{row.source}</td></tr>})}</tbody></>:tab==="predictions"?<><thead><tr><th>Generated</th><th>Current</th><th>Predicted</th><th>Horizon</th><th>Condition</th><th>Confidence</th><th>Model</th></tr></thead><tbody>{rows.map(raw=>{const row=raw as LogsPayload["predictions"][number];return <tr key={row.id}><td>{new Date(row.generatedAt).toLocaleString()}</td><td>{n(row.currentWaveHeight)} m</td><td>{n(row.predictedWaveHeight)} m</td><td>{row.horizonMinutes} min</td><td>{row.seaCondition}</td><td>{row.confidence}%</td><td>{row.model} {row.modelVersion}</td></tr>})}</tbody></>:tab==="alerts"?<><thead><tr><th>Timestamp</th><th>Code</th><th>Severity</th><th>Message</th><th>Telemetry ID</th></tr></thead><tbody>{rows.map(raw=>{const row=raw as LogsPayload["alerts"][number];return <tr key={row.id}><td>{new Date(row.recordedAt).toLocaleString()}</td><td>{row.code}</td><td><em className={`table-severity is-${row.severity}`}>{row.severity}</em></td><td>{row.message}</td><td>#{row.telemetryId}</td></tr>})}</tbody></>:<><thead><tr><th>Timestamp</th><th>Event</th><th>Target</th><th>Status</th><th>Detail</th></tr></thead><tbody>{rows.map(raw=>{const row=raw as LogsPayload["events"][number];return <tr key={row.id}><td>{new Date(row.recordedAt).toLocaleString()}</td><td>{row.eventType}</td><td>{row.target||"--"}</td><td>{row.status}</td><td>{JSON.stringify(row.detail)}</td></tr>})}</tbody></>}</table>{!loading&&!rows.length&&<div className="log-empty">No matching {tab} records.</div>}</div><footer>Showing latest {logs[tab].length} local records · exports contain the current filtered view.</footer></article></section>}
