import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./styles.css";
import "./wave.css";
import "./motion.css";
import "leaflet/dist/leaflet.css";
import "./gps.css";
import "./power.css";
import "./system.css";
import "./alerts.css";
import "./toast.css";
import "./logs.css";
import "./settings.css";
import "./polish.css";
import "./light.css";
import "./sidebar-control.css";
import "./wave-polish.css";
import "./command-center.css";
import "./wave-report.css";

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
