import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./styles.css";
import "./wave.css";
import "./motion.css";
import "leaflet/dist/leaflet.css";
import "./gps.css";
import "./power.css";
import "./system.css";
import "./alerts.css";
import "./toast.css";
import "./logs.css";
import "./settings.css";
import "./polish.css";
import "./light.css";
import "./sidebar-control.css";
import "./wave-polish.css";
import "./command-center.css";
import "./wave-report.css";
import "./chromatic-system.css";
import "./charts-pro.css";
import "./prediction-inputs.css";
import "./industrial-theme.css";
import "./scenario.css";
import "./overview.css";
import "./minimal-pages.css";
import "./split-wave.css";
import "./input-bars-fix.css";
import "./minimal-color.css";
import "./engineering.css";
import "./operator-simple.css";
import "./grouped-sensors.css";
import "./calm-operator-theme.css";

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
