import { useState } from "react";
import { Activity, Compass, Gauge, Waves } from "lucide-react";
import MotionScene from "./MotionScene";
import type { DashboardData } from "./types";

const n=(value:number|null|undefined,digits=1)=>value==null?"--":value.toFixed(digits);
type MotionScenario="current"|"calm"|"moderate"|"rough"|"offline";
const scenarios:{id:MotionScenario;label:string;wave:number|null;description:string}[]=[
 {id:"current",label:"Current data",wave:null,description:"Uses the latest pressure-based wave estimate."},
 {id:"calm",label:"Calm",wave:.35,description:"Demonstrates small, gentle water movement."},
 {id:"moderate",label:"Moderate",wave:1.2,description:"Demonstrates noticeable but manageable waves."},
 {id:"rough",label:"Rough",wave:2.8,description:"Demonstrates strong buoy movement in rough water."},
 {id:"offline",label:"Pressure offline",wave:.05,description:"Demonstrates the display when pressure data is unavailable."},
];
export default function MotionPage({data}:{data:DashboardData}){
 const [scenario,setScenario]=useState<MotionScenario>("current");
 const {wave}=data,selected=scenarios.find(item=>item.id===scenario)!,scenarioActive=scenario!=="current",modelWave=selected.wave??wave.waveHeight??.4,rough=modelWave>=2.5,alerts=data.status.alerts.map(alert=>`${alert.code} ${alert.message}`.toLowerCase()),liveFault=alerts.some(value=>value.includes("sensor"))?"sensor" as const:alerts.some(value=>value.includes("heat")||value.includes("temperature"))?"thermal" as const:alerts.some(value=>value.includes("battery")||value.includes("power"))?"power" as const:null,fault=scenario==="offline"?"sensor" as const:scenarioActive?null:liveFault,source=scenarioActive?"demo scenario":data.status.dataSource;
 return <section className="content motion-page"><div className="page-head"><div><span>PRESSURE-DRIVEN VISUAL MODEL</span><h1>Buoy motion</h1><p>The 3D buoy response is generated from the pressure-based estimated wave height. No IMU, roll sensor, or pitch sensor is used.</p></div><em className="sensor-chip"><i/> PRESSURE MODEL · {data.status.dataSource.toUpperCase()}</em></div>
 <article className="panel scenario-panel"><header><div><span>DEMONSTRATION CONTROLS</span><h2>Choose a water condition</h2></div><em>{scenarioActive?"SIMULATED SCENARIO":"LIVE / CURRENT INPUT"}</em></header><div className="scenario-buttons" role="group" aria-label="Buoy motion demonstration scenario">{scenarios.map(item=><button key={item.id} type="button" className={scenario===item.id?"active":""} aria-pressed={scenario===item.id} onClick={()=>setScenario(item.id)}>{item.label}</button>)}</div><p>{selected.description} {scenarioActive&&"This preset changes only the 3D demonstration and does not overwrite sensor data."}</p></article>
 <div className="motion-layout"><article className="panel twin-panel"><header><div><span>FALCON-01 PRESSURE RESPONSE</span><h2>Estimated water-surface movement</h2></div><em>{scenario==="offline"?"PRESSURE OFFLINE":rough?"ROUGH SEA MODEL":"WAVE MODEL"}</em></header><MotionScene telemetry={{yaw:data.gps.headingDegrees||0,wave:modelWave,rough,fault,source}}/><footer>{scenario==="offline"?"Pressure input is unavailable in this demonstration; the sensor assembly is highlighted for identification.":"Heave and tilt follow a modeled water surface scaled by the pressure-based wave estimate; they are not measured orientation values."}</footer></article>
 <aside className="motion-side"><article className="panel pose-readout"><header><div><span>{scenarioActive?"DEMO INPUT":"PRESSURE INPUT"}</span><h2>Movement basis</h2></div><Waves/></header><dl><div><dt>Filtered pressure</dt><dd>{scenarioActive?"Not used":`${n(wave.filteredPressure,2)} kPa`}</dd></div><div><dt>Pressure baseline</dt><dd>{scenarioActive?"Not used":`${n(wave.pressureBaseline,2)} kPa`}</dd></div><div><dt>Wave estimate</dt><dd>{scenario==="offline"?"Unavailable":`${n(modelWave,2)} m`}</dd></div><div><dt>Heading context</dt><dd>{n(data.gps.headingDegrees)}°</dd></div></dl></article>
 <article className="panel motion-quality"><header><div><span>{scenarioActive?"SCENARIO STATUS":"ESTIMATE QUALITY"}</span><h2>Visualization input</h2></div><Gauge/></header><strong>{scenarioActive?(scenario==="offline"?"OFFLINE":"DEMO"):`${Math.round((wave.quality||0)*100)}%`}</strong><p>{scenarioActive?"A labeled local preset for presentation and training. Live readings remain unchanged.":"Quality indicator of the pressure-based wave estimate driving this visual model."}</p><div className="quality-line"><i style={{width:`${scenarioActive?(scenario==="offline"?0:100):(wave.quality||0)*100}%`}}/></div></article>
 <article className="panel axes"><span><Activity/> Heave and tilt <b>Modeled from wave surface</b></span><span><Compass/> Direction <b>GPS heading context</b></span></article></aside></div></section>
}
