import { Activity, Compass, Gauge, Waves } from "lucide-react";
import MotionScene from "./MotionScene";
import type { DashboardData } from "./types";

const n=(value:number|null|undefined,digits=1)=>value==null?"--":value.toFixed(digits);
export default function MotionPage({data}:{data:DashboardData}){
 const {wave}=data,modelWave=wave.valid?Math.max(0,wave.waveHeight??0):0,rough=modelWave>=2.5,alerts=data.status.alerts.map(alert=>`${alert.code} ${alert.message}`.toLowerCase()),liveFault=alerts.some(value=>value.includes("sensor"))?"sensor" as const:alerts.some(value=>value.includes("heat")||value.includes("temperature"))?"thermal" as const:alerts.some(value=>value.includes("battery")||value.includes("power"))?"power" as const:null,fault=!wave.valid?"sensor" as const:liveFault,source=data.status.dataSource;
 return <section className="content motion-page"><div className="page-head"><div><span>PRESSURE-DRIVEN VISUAL MODEL</span><h1>Buoy motion</h1><p>The 3D buoy response is generated from the pressure-based estimated wave height. No IMU, roll sensor, or pitch sensor is used.</p></div><em className="sensor-chip"><i/> PRESSURE MODEL · {data.status.dataSource.toUpperCase()}</em></div>

 <div className="motion-layout"><article className="panel twin-panel"><header><div><span>FALCON-01 PRESSURE RESPONSE</span><h2>Estimated water-surface movement</h2></div><em>{!wave.valid?"PRESSURE OFFLINE":rough?"ROUGH SEA MODEL":"WAVE MODEL"}</em></header><MotionScene telemetry={{yaw:data.gps.headingDegrees||0,wave:modelWave,rough,fault,source}}/><footer>{!wave.valid?"Pressure input is unavailable. Wave-driven movement settles until readings return.":"Heave and tilt follow a modeled water surface scaled by the pressure-based wave estimate; they are not measured orientation values."}</footer></article>
 <aside className="motion-side"><article className="panel pose-readout"><header><div><span>PRESSURE INPUT</span><h2>Movement basis</h2></div><Waves/></header><dl><div><dt>Filtered pressure</dt><dd>{`${n(wave.filteredPressure,2)} kPa`}</dd></div><div><dt>Pressure baseline</dt><dd>{`${n(wave.pressureBaseline,2)} kPa`}</dd></div><div><dt>Wave estimate</dt><dd>{!wave.valid?"Unavailable":`${n(modelWave,2)} m`}</dd></div><div><dt>Heading context</dt><dd>{n(data.gps.headingDegrees)}°</dd></div></dl></article>
 <article className="panel motion-quality"><header><div><span>ESTIMATE QUALITY</span><h2>Visualization input</h2></div><Gauge/></header><strong>{!wave.valid?"OFFLINE":`${Math.round((wave.quality||0)*100)}%`}</strong><p>Quality indicator of the pressure-based wave estimate driving this visual model.</p><div className="quality-line"><i style={{width:`${!wave.valid?0:(wave.quality||0)*100}%`}}/></div></article>
 <article className="panel axes"><span><Activity/> Heave and tilt <b>Modeled from wave surface</b></span><span><Compass/> Direction <b>GPS heading context</b></span></article></aside></div></section>
}
