import { useEffect, useState } from "react";
import { Bell, CheckCircle2, Clock3, Gauge, RefreshCw, RotateCcw, Settings, Wrench } from "lucide-react";
import { getScenario, requestRestart, setScenario, startCalibration } from "./api";
import type { ScenarioState } from "./types";
const labels:Record<string,string>={normal:"Normal operation",rough_sea:"Rough sea",low_battery:"Low battery",overheating:"Internal overheating",sensor_fault:"Wave sensor failure",tamper_alert:"Tamper alert",geofence_alert:"Geofence alert"};
export default function SettingsPage({horizon,onHorizon,pollInterval,onPollInterval,onRefresh}:{horizon:number;onHorizon:(value:number)=>void;pollInterval:number;onPollInterval:(value:number)=>void;onRefresh:()=>void}){const [scenario,setScenarioState]=useState<ScenarioState|null>(null),[busy,setBusy]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[sensor,setSensor]=useState("water-pressure"),notification=typeof Notification==="undefined"?"unsupported":Notification.permission;
 useEffect(()=>{getScenario().then(setScenarioState).catch(reason=>setError(reason.message))},[]);const run=async(name:string,action:()=>Promise<unknown>,message:string)=>{setBusy(name);setError(null);try{await action();setNotice(message);onRefresh()}catch(reason){setError(reason instanceof Error?reason.message:"Action failed")}finally{setBusy(null)}};
 const changeScenario=(value:string)=>run("scenario",async()=>setScenarioState(await setScenario(value)),`${labels[value]} scenario applied.`);const enableNotifications=async()=>{if(typeof Notification==="undefined"){setError("Browser notifications are not supported.");return}const permission=await Notification.requestPermission();setNotice(`Browser notification permission: ${permission}.`)};
 const restart=()=>{if(!confirm("Send an ESP32 restart request? This demo command is recorded in the local event log."))return;run("restart",()=>requestRestart("esp32"),"ESP32 restart request accepted and logged.")};const calibrate=()=>{if(!confirm(`Start ${sensor} calibration? Keep the buoy stable during calibration.`))return;run("calibrate",()=>startCalibration(sensor),`${sensor} calibration started and logged.`)};
 return <section className="content settings-page"><div className="page-head"><div><span>LOCAL CONFIGURATION</span><h1>Station settings</h1><p>Presentation preferences and controlled maintenance actions for this browser and edge service.</p></div><em className="sensor-chip"><i/> SETTINGS · LOCAL</em></div>{notice&&<div className="settings-notice"><CheckCircle2/>{notice}</div>}{error&&<div className="inline-error">{error}</div>}
 <div className="settings-grid"><article className="panel settings-card"><header><div><span>DATA REFRESH</span><h2>Dashboard timing</h2></div><Clock3/></header><label className="setting-field"><span>Update interval<small>How often the dashboard refreshes its readings</small></span><select value={pollInterval} onChange={e=>onPollInterval(Number(e.target.value))}><option value="1000">1 second</option><option value="2000">2 seconds</option><option value="5000">5 seconds</option></select></label><label className="setting-field"><span>AI prediction horizon<small>How far ahead FALCON estimates wave height on the Overview</small></span><select value={horizon} onChange={e=>onHorizon(Number(e.target.value))}><option value="5">5 minutes</option><option value="10">10 minutes</option><option value="15">15 minutes</option></select></label></article>
 <article className="panel settings-card"><header><div><span>NOTIFICATIONS</span><h2>Warning behavior</h2></div><Bell/></header><div className="notification-setting"><Bell/><span>In-dashboard alerts<b>Always enabled</b><small>Badge and toast while this dashboard is open</small></span></div><button className="settings-button" onClick={enableNotifications} disabled={notification==="granted"}>{notification==="granted"?"Browser notifications enabled":"Enable browser notifications"}</button><p>Permission: <b>{notification.toUpperCase()}</b></p></article>
 <article className="panel settings-card"><header><div><span>DEMONSTRATION</span><h2>Simulated conditions</h2></div><Gauge/></header><label className="setting-field"><span>Test condition<small>Clearly labeled simulated readings</small></span><select value={scenario?.active||"normal"} disabled={busy==="scenario"||!scenario?.available} onChange={e=>changeScenario(e.target.value)}>{(scenario?.scenarios||["normal"]).map(value=><option key={value} value={value}>{labels[value]||value}</option>)}</select></label><p>Use these conditions only for software demonstrations and testing.</p></article>
 <article className="panel settings-card maintenance"><header><div><span>SENSOR MAINTENANCE</span><h2>Calibration</h2></div><Wrench/></header><label className="setting-field"><span>Sensor channel<small>Creates an auditable calibration event</small></span><select value={sensor} onChange={e=>setSensor(e.target.value)}><option value="water-pressure">Water pressure</option><option value="wind">Wind sensor</option><option value="gps">GPS geofence</option><option value="security">Security inputs</option></select></label><button className="settings-button" onClick={calibrate} disabled={busy==="calibrate"}><RefreshCw/> {busy==="calibrate"?"Starting…":"Start calibration"}</button></article>
 <article className="panel settings-card maintenance danger-zone"><header><div><span>CONTROLLED RESTART</span><h2>ESP32 maintenance</h2></div><RotateCcw/></header><p>This sends a restart request to the edge API. In simulator mode it records the request without claiming that physical hardware restarted.</p><button className="settings-button is-danger" onClick={restart} disabled={busy==="restart"}><RotateCcw/> {busy==="restart"?"Requesting…":"Restart ESP32"}</button></article></div><footer className="settings-footer"><Settings/> Preferences are stored in this browser. Maintenance commands are stored in the local event database.</footer></section>}
