import { Activity, Cpu, Database, HardDrive, MemoryStick, Network, Radio, Server, ShieldCheck, Wifi } from "lucide-react";
import type { DashboardData } from "./types";
const n=(value:number|null|undefined,digits=0)=>value==null?"--":value.toFixed(digits);
const uptime=(seconds:number)=>{const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return `${d?`${d}d `:""}${h}h ${m}m ${s}s`};
function Node({icon:Icon,label,value}:{icon:typeof Cpu;label:string;value:string}){const good=["ONLINE","CONNECTED","SIMULATED"].includes(value);return <article className="system-node"><Icon/><span>{label}<b className={good?"good":"warn"}>{value}</b></span><i className={good?"is-good":""}/></article>}
function Resource({icon:Icon,label,value,suffix="%"}:{icon:typeof Cpu;label:string;value:number|null;suffix?:string}){const width=suffix==="%"?Math.max(0,Math.min(100,value||0)):Math.max(0,Math.min(100,((value||-100)+100)*1.5));return <article><Icon/><span>{label}<b>{n(value)}{suffix}</b></span><div><i style={{width:`${width}%`}}/></div></article>}
export default function SystemPage({data}:{data:DashboardData}){const {status}=data,healthy=status.system==="ONLINE"&&!status.lastError,sensorPercent=status.sensorsExpected?status.sensorsOnline/status.sensorsExpected*100:0;return <section className="content system-page"><div className="page-head"><div><span>EDGE CONTROLLER & DIAGNOSTICS</span><h1>System health</h1><p>Connectivity, compute resources, sensor availability, and local service state.</p></div><em className={`sensor-chip ${healthy?"":"is-warning"}`}><i/> {healthy?"ALL CORE SERVICES ONLINE":"ATTENTION REQUIRED"}</em></div>
 <div className="health-banner panel"><div className={`health-orb ${healthy?"is-good":"is-warning"}`}><ShieldCheck/></div><div><span>OVERALL HEALTH</span><h2>{status.system}</h2><p>{healthy?"The local edge pipeline is operating normally.":status.lastError||"One or more services require attention."}</p></div><dl><div><dt>Monitoring</dt><dd>{status.monitoring?"ACTIVE":"STOPPED"}</dd></div><div><dt>Uptime</dt><dd>{uptime(status.uptimeSeconds)}</dd></div><div><dt>Source</dt><dd>{status.dataSource.toUpperCase()}</dd></div></dl></div>
 <div className="system-grid"><article className="panel connectivity"><header><div><span>SERVICE TOPOLOGY</span><h2>Local connectivity</h2></div><Network/></header><div className="node-grid"><Node icon={Radio} label="ESP32" value={status.esp32}/><Node icon={Server} label="Mini PC" value={status.miniPc}/><Node icon={Activity} label="UART link" value={status.uart}/><Node icon={Database} label="Local API" value={status.api}/></div><footer>Simulator labels are explicit and do not represent installed hardware.</footer></article>
 <article className="panel sensors-card"><header><div><span>SENSOR BUS</span><h2>Approved sensor availability</h2></div><Cpu/></header><div className="sensor-score"><strong>{status.sensorsOnline}<small>/{status.sensorsExpected}</small></strong><span>ONLINE</span></div><div className="sensor-progress"><i style={{width:`${sensorPercent}%`}}/></div><p>{status.sensorsOnline===status.sensorsExpected?"All expected telemetry channels are reporting.":`${status.sensorsExpected-status.sensorsOnline} sensor channel requires attention.`}</p></article>
 <article className="panel resources"><header><div><span>MINI PC RESOURCES</span><h2>Compute utilization</h2></div><HardDrive/></header><div className="resource-grid"><Resource icon={Cpu} label="CPU usage" value={status.cpuUsage}/><Resource icon={MemoryStick} label="RAM usage" value={status.memoryUsage}/><Resource icon={HardDrive} label="Storage" value={status.storageUsage}/><Resource icon={Wifi} label="Wi-Fi signal" value={status.wifiSignalDbm} suffix=" dBm"/></div></article>
 <article className="panel diagnostics"><header><div><span>DIAGNOSTIC SUMMARY</span><h2>Current findings</h2></div><ShieldCheck/></header>{status.lastError?<div className="diagnostic-error"><b>EDGE ERROR</b><span>{status.lastError}</span></div>:status.alerts.length?<ul>{status.alerts.map((alert,index)=><li key={`${alert.code}-${index}`}><i/><span><b>{alert.code}</b>{alert.message}</span><em>{alert.severity}</em></li>)}</ul>:<div className="diagnostic-clear"><ShieldCheck/><span><b>No active faults</b>All monitored services and sensors are nominal.</span></div>}<footer>Firmware v{status.version} · Dashboard v{status.dashboardVersion}</footer></article></div></section>}
