import { useId, useState } from "react";
export type ChartPoint={value:number|null;recordedAt?:string};
type Props={points:ChartPoint[];unit:string;color:string;secondaryColor?:string;primaryLabel?:string;secondaryLabel?:string;forecast?:number|null;forecastLabel?:string;minimumZero?:boolean;threshold?:number;label:string;variant?:"standard"|"minimal";showSecondary?:boolean;interactive?:boolean};
const smoothPath=(points:number[][])=>{if(!points.length)return"";if(points.length===1)return`M ${points[0][0]} ${points[0][1]}`;let path=`M ${points[0][0]} ${points[0][1]}`;for(let i=0;i<points.length-1;i++){const p=points[Math.max(0,i-1)],c=points[i],n=points[i+1],a=points[Math.min(points.length-1,i+2)];path+=` C ${c[0]+(n[0]-p[0])/6} ${c[1]+(n[1]-p[1])/6}, ${n[0]-(a[0]-c[0])/6} ${n[1]-(a[1]-c[1])/6}, ${n[0]} ${n[1]}`}return path};
const timeLabel=(value?:string)=>value?new Date(value).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"}):"--";
export default function TelemetryChart({points,unit,color,secondaryColor="#c49355",primaryLabel="Measured telemetry",secondaryLabel="Smoothed trend",forecast,forecastLabel="FORECAST",minimumZero=false,threshold,label,variant="standard",showSecondary=true,interactive=true}:Props){
 const [selected,setSelected]=useState<number|null>(null),gradientId=`chart-fill-${useId().replaceAll(":","")}`,valid=points.filter((p):p is ChartPoint&{value:number}=>p.value!=null).slice(-60);if(valid.length<2)return <div className="pro-chart-empty">Collecting {label.toLowerCase()} history...</div>;
 const values=valid.map(p=>p.value),trend:number[]=[];values.forEach((v,i)=>trend.push(i===0?v:trend[i-1]*.72+v*.28));const all=forecast==null?[...values,...trend]:[...values,...trend,forecast],rawMin=Math.min(...all),rawMax=Math.max(...all),rawRange=Math.max(.01,rawMax-rawMin),padding=Math.max(rawRange*.2,unit==="%"?.15:.05),min=minimumZero?Math.max(0,rawMin-padding):rawMin-padding,max=rawMax+padding,range=Math.max(.01,max-min),left=58,right=forecast==null?714:642,top=26,bottom=214,toY=(v:number)=>bottom-(v-min)/range*(bottom-top),toX=(i:number)=>left+i/Math.max(1,valid.length-1)*(right-left),xy=values.map((v,i)=>[toX(i),toY(v)]),trendXy=trend.map((v,i)=>[toX(i),toY(v)]),line=smoothPath(xy),trendLine=smoothPath(trendXy),area=`${line} L ${right} ${bottom} L ${left} ${bottom} Z`,last=xy.at(-1)!,trendLast=trendXy.at(-1)!,forecastY=forecast==null?null:toY(forecast),ticks=[0,1,2,3,4],mid=Math.floor((valid.length-1)/2);
 const selectedIndex=selected!=null&&selected<valid.length?selected:null,selectedPoint=selectedIndex==null?null:xy[selectedIndex],selectedX=selectedPoint?Math.min(636,Math.max(70,selectedPoint[0]-64)):0,selectedY=selectedPoint?Math.max(31,selectedPoint[1]-52):0;
 return <div className={`pro-chart-shell is-${variant}`}><div className="pro-chart-legend"><span><i style={{background:color}}/>{primaryLabel}</span>{showSecondary&&<span><i style={{background:secondaryColor}}/>{secondaryLabel}</span>}{forecast!=null&&<span><i className="is-forecast"/>AI forecast</span>}{interactive&&<small>Click a point for details</small>}</div><svg className="pro-chart" viewBox="0 0 760 260" role="img" aria-label={label}><defs><linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity={variant==="minimal"?"0":".2"}/><stop offset="1" stopColor={color} stopOpacity=".01"/></linearGradient></defs>
 {ticks.map(row=>{const y=top+(bottom-top)*row/4,value=max-(max-min)*row/4;return <g key={row}><line x1={left} y1={y} x2="714" y2={y} className="pro-grid"/><text x={left-11} y={y+4} textAnchor="end" className="pro-axis">{value.toFixed(unit==="%"?1:2)}{unit}</text></g>})}{forecastY!=null&&variant==="standard"&&<rect x={right} y={top} width={714-right} height={bottom-top} className="forecast-zone"/>}{threshold!=null&&threshold>=min&&threshold<=max&&<g><line x1={left} y1={toY(threshold)} x2="714" y2={toY(threshold)} className="threshold-line"/><text x="708" y={toY(threshold)-7} textAnchor="end" className="threshold-label">LIMIT {threshold}{unit}</text></g>}
 <path d={area} fill={`url(#${gradientId})`} className="pro-area"/><path d={line} style={{stroke:color}} className="pro-line is-measured"/>{showSecondary&&<path d={trendLine} style={{stroke:secondaryColor}} className="pro-line is-trend"/>}{xy.map((p,i)=>interactive?<g key={i} role="button" tabIndex={0} aria-label={`${timeLabel(valid[i].recordedAt)}, ${label.toLowerCase()} ${values[i].toFixed(2)}${unit}`} onClick={()=>setSelected(i)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setSelected(i)}}}><circle cx={p[0]} cy={p[1]} r="14" className="pro-hit"/><circle cx={p[0]} cy={p[1]} r={selectedIndex===i?5:2.3} style={{fill:color}} className={`history-dot ${selectedIndex===i?"is-selected":""}`}/></g>:<circle key={i} cx={p[0]} cy={p[1]} r="2.3" style={{fill:color}} className="history-dot"/>)}<circle cx={last[0]} cy={last[1]} r="4.5" style={{fill:color}} className="current-dot"/>{showSecondary&&<circle cx={trendLast[0]} cy={trendLast[1]} r="4" style={{fill:secondaryColor}} className="trend-dot"/>}
 {forecastY!=null&&<g><path d={`M ${trendLast[0]} ${trendLast[1]} C ${trendLast[0]+24} ${trendLast[1]}, ${right+37} ${forecastY}, 714 ${forecastY}`} className="pro-forecast"/><circle cx="714" cy={forecastY} r="6" className="forecast-dot"/><text x="706" y={forecastY-12} textAnchor="end" className="forecast-value">{forecast!.toFixed(2)}{unit}</text>{variant==="standard"&&<text x={right+8} y={top+14} className="forecast-zone-label">{forecastLabel}</text>}</g>}{selectedPoint&&selectedIndex!=null&&<g className="chart-tooltip"><line x1={selectedPoint[0]} y1={selectedPoint[1]} x2={selectedPoint[0]} y2={bottom} /><rect x={selectedX} y={selectedY} width="128" height="42" rx="7"/><text x={selectedX+10} y={selectedY+17}>{values[selectedIndex].toFixed(2)}{unit}</text><text x={selectedX+10} y={selectedY+32}>{timeLabel(valid[selectedIndex].recordedAt)}</text></g>}<text x={left} y="245" className="pro-time">{timeLabel(valid[0].recordedAt)}</text><text x={(left+right)/2} y="245" textAnchor="middle" className="pro-time">{timeLabel(valid[mid].recordedAt)}</text><text x={right} y="245" textAnchor="end" className="pro-time">{timeLabel(valid.at(-1)?.recordedAt)}</text></svg>{selectedIndex!=null&&<button className="chart-selected-value" onClick={()=>setSelected(null)}><span>Selected reading</span><b>{values[selectedIndex].toFixed(2)}{unit}</b><time>{timeLabel(valid[selectedIndex].recordedAt)}</time><i>×</i></button>}</div>;
}
