export const inspections = {
  pressure: {name:'Underwater Pressure', function:'Senses pressure under the water. That reading travels to shore, where it becomes an estimated wave height.', how:'Underwater sensor feels wave pressure pushing through the water. Deeper means a weaker signal.', acquire:'ESP32 reads it every cycle, stamps the time, flags bad values. No wave math happens on the buoy.', data:['Pressure','Timestamp','Quality state','Calibration status'], flow:['PRESSURE','SHORE PROCESSING','ESTIMATED WAVE HEIGHT'], status:'CALIBRATION REQUIRED', note:'HPT604 deployment candidate. Pressure is the input—not a direct wave-height reading.',specs:['Holykell HPT604 Type A (candidate)','Reads 0–2 m water depth as pressure','4–20 mA signal · ±0.5% accuracy','Bench backup: Bar02 (short tests only)']},
  wind: {name:'Wind Observation', function:'Measures wind speed and direction at the buoy.', how:'Spinning cups measure speed; the vane points the direction.', acquire:'ESP32 counts spins for speed, reads the vane angle, timestamps both.', data:['Wind speed','Wind direction','Timestamp','Sensor quality'], flow:['WIND SENSOR','ESP32'], status:'VALIDATION PENDING', note:'Wind is a primary Phase 1 measurement; comparison against a reference is still pending.',specs:['SparkFun Weather Meter Kit SEN-15901 (prototype)','Reed-switch pulses · 1 pulse/s = 1.492 mph','Vane: 16 positions, 8 cardinal via ADC divider','Marine durability unproven — supervised prototype']},
  gps: {name:'GPS / Position', function:'Provides position and timing for the system.', how:'Listens to satellites for position and exact time. Draws the boundary line that catches drift.', acquire:'Position and time ride along on every record. Drift watch, not wave data.', data:['Latitude','Longitude','GPS quality / status','Timestamp'], flow:['GPS','ESP32','SECURITY LOGIC'], status:'VALIDATION PENDING', note:'Normal GPS scatter is not theft. Quality checks and persistence come first.',specs:['Adafruit Ultimate GPS, PID 746','Position + time + geofence boundary','External antenna optional','Supporting telemetry only']},
  battery: {name:'Battery / Energy Storage', function:'Stores solar energy and powers the buoy electronics when the sun is low.', how:'Banks daytime solar power for night and cloudy hours.', acquire:'Voltage and charge level measured every cycle, sent inside each frame.', data:['Battery state','Solar / charging state','System health','Timestamp'], flow:['SOLAR','BATTERY','ELECTRONICS'], status:'ENERGY STORAGE / MONITORING', note:'LiFePO4 battery is the energy-storage element. Performance still needs measured validation.',specs:['LiFePO4 12 V, 20–30 Ah (plan)','Monitored via Adafruit INA260, PID 4226','Measured validation pending']},
  solar: {name:'Solar / Power', function:'Collects and monitors the energy that runs the buoy.', how:'Panels turn sunlight into charging current for the battery.', acquire:'Panel voltage and current sampled each cycle. Energy info only.', data:['Battery state','Solar / power status','Voltage / current','Energy telemetry'], flow:['SOLAR','BATTERY','ELECTRONICS'], status:'NO MEASURED POWER CLAIM', note:'Energy flow is conceptual. No measured value is invented.',specs:['40–60 W panel candidate','LiFePO4 MPPT controller','Final rating follows measured buoy load']},
  esp32: {name:'ESP32 Controller', function:'Reads the sensors, checks timestamps and quality, and prepares LoRa telemetry.', how:'Reads every sensor in turn, checks each value, packs one timestamped frame.', acquire:'Read, check, pack, send — every 4.8 seconds. Bad readings are flagged, never hidden.', data:['Sensor records','Timestamp / quality','Telemetry packet','Buffered records'], flow:['SENSORS','ESP32','PACKET','LoRa'], status:'BUOY-SIDE CONTROLLER', note:'Inspecting the actual control enclosure. Main processing and AI remain on shore.',specs:['Espressif ESP32-DevKitC V4, WROOM-32E','38-pin — GPIO16/17 required (no WROVER)','4.8 s acquisition cycle']},
  lora: {name:'LoRa Transceiver', function:'Provides radio link from buoy to shore Bay Station for telemetry.', how:'Small radio, long reach, tiny power. Short packets over water.', acquire:'Each frame gets a number. Unsent ones wait with their original timestamps.', data:['Link state','Packet sequence','Buffer depth','RSSI'], flow:['ESP32','LoRa TX','LoRa RX','BAY STATION'], status:'ILLUSTRATIVE PLACEMENT', note:'Illustrative placement uses the NAVIGATION_LIGHT model from the upper equipment deck. No field range or hardware claim.',specs:['Candidate: Ai-Thinker Ra-02 (SX1276, 433 MHz)','Long-range class — pilot needs only 500 m–1 km','Low power: short packets, battery-friendly','Legal PH band confirmation + field range test still pending']}
};
export function easeInspection(value){const t=Math.max(0,Math.min(1,value));return t*t*t*(t*(t*6-15)+10);}
export function inspectionDistance(size,aspect){return Math.max(.48,size*.9/Math.tan(21*Math.PI/180)/Math.min(1,aspect));}
export function inspectionFrame(center,size,aspect,mobile,currentEye=null){
  const distance=inspectionDistance(size,aspect);
  // Approach from the viewer's current side of the model so inspection feels like
  // a continuous camera move instead of a jump to an arbitrary compass direction.
  let direction=currentEye
    ? currentEye.map((v,i)=>v-center[i])
    : [center[0],.3,center[2]];
  if(Math.hypot(...direction)<.1)direction=[1,.35,1];
  const length=Math.hypot(...direction);direction=direction.map(v=>v/length);
  const right=[direction[2],0,-direction[0]],r=Math.max(.001,Math.hypot(...right));
  const eye=center.map((v,i)=>v+direction[i]*distance);
  const aim=center.map((v,i)=>v+(mobile&&i===1?-distance*.08:0));
  return {distance,eye,aim};
}
